image: node:latest

stages:
  - installation
  - coverage

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: installation
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
coverage:
  script:
    - npm run coverag
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml
